thruster_manager:
  tf_prefix: rov_example
  base_link: base_link
  thruster_topic_prefix: thrusters/
  thruster_topic_suffix: /input
  thruster_frame_base: thruster_
  max_thrust: 88.96 #Each thruster has about 20 pounds of thrust.
  timeout: -1
  update_rate: 50
  conversion_fcn: custom
  conversion_fcn: proportional
  conversion_fcn_params:
    gain: 0.00031